### PR TITLE
Updated Spectre.Console to 0.40

### PR DESCRIPTION
**Pull request by olegtarasov**

### CODE REVIEW

**Comment by SuperJMN** [comment]
Why isn't this merged already? :)

**Comment by AntyaDev** [comment]
@SuperJMN 
We tried version 0.39 and noticed that it produced some errors.
I didn't have a chance to check 0.40 version.

@olegtarasov Have you tried to test that it works?

**Comment by olegtarasov** [comment]
@AntyaDev I've just tested `0.42` and it works in my case, but so did `0.39`.

**Comment by AntyaDev** [comment]
Hi @olegtarasov 
Can you please add some integration tests? (especially that tests progress bar)

**Comment by olegtarasov** [comment]
@AntyaDev Sorry, but I'm afraid I won't be able to carve out the time for integration tests :(  I use this library in my pet project with me as the only developer and user, and I really don't mind occasional glitches with console output (not that I've experienced any). I know this is not an ideal approach for an open source contribution, but unfortunately I have to choose between writing tests and moving forward a project that is important to me.

**Pull request closed without merging**
